### ISSUE TITLE
Error when compiling mediabenchmark adpcm/rawcaudio

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#1]
**Compiling**
`llc -O3 -unison-verbose -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o adpcm.unison.S adpcm.unison.ll`

**Assembling**
`hexagon-as -mv4 --gstabs+ -o adpcm.unison.o adpcm.unison.S`
adpcm.unison.S: Assembler messages:
adpcm.unison.S:10: `Error: low 3 bits of immediate -20 must be zero`
adpcm.unison.S:10: `Error: invalid instruction memd(r29+#-20) =r17:16`
adpcm.unison.S:48: `Error: register 'r12' used with '.new' but not validly modified in the same packet.`
adpcm.unison.S:137: `Error: low 3 bits of immediate 4 must be zero`
adpcm.unison.S:137: `Error: invalid instruction 'r17:16 =memd(r29+#4)'`

[adpcm.zip](https://github.com/unison-code/unison/files/774497/adpcm.zip)

**Comment by robcasloz** [comment]
Hi, thanks for the report @maerem! Commit 56b3e1bf4931d7955f1ce81f4e6ef06bf0dbc775 should fix the issue in line 48. Will keep working in the remaining problems.
