### ISSUE TITLE
Simulator crashes, exception 0x20, Misaligned Load @ 0x21(?) - Benchmark: djpeg, Function: h2v2_fancy_upsample

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#12]
`/home/martip/Qualcomm/HEXAGON_Tools/6.4.06/qc/bin/hexagon-sim djpeg-unison --timing -- -dct int -ppm -outfile testout.ppm  ../testorig.jpg`

> Hexagon-sim INFO: the rev_id used in the simulation is 0x00000084 (v4m)
> CRASH from thread 0!
> I think the exception was: 0x20, Misaligned Load @ 0x21
> 
> Register Dump (r0 clobbered, pc subject to prior action by the exception handler):
> r00=000000cd r01=0002cc84 r02=0002ebd4 r03=00000002
> r04=00000004 r05=00000007 r06=00000002 r07=00030f6c
> r08=00000082 r09=0000080c r10=00030f6e r11=0000020a
> r12=0000082f r13=0003283a r14=000007b7 r15=000327c2
> r16=00000001 r17=00000007 r18=babebeef r19=babebeef
> r20=babebeef r21=babebeef r22=00000001 r23=babebeef
> r24=0412af58 r25=0000f034 r26=0412b010 r27=0412af64
> r28=00000000 r29=0412af00 r30=0412af28 r31=00012db4
> sa0=00013670 lc0=00000001 sa1=0000d2f0 lc1=00000001
> p30=ff000000  m0=00000000  m1=00000000 usr=00010000
>  pc=00000894 ugp=00000000  gp=0002b000 elr=00012db4
> badva0=0412b1f8 badva1=00000021
> ssr=00640020 ccr=00130000 tid=00000000 imask=00000000
> evb=00005000 modectl=00000001 syscfg=0083007f ipend=00000000
> 
> Memory hex dump close to the top of the stack in byte-order:
>  -- unable to figure out the stack size, assuming 0x100000
>  stack-bottom: 0x0412b200 stack-top: 0x0412af00
> 0x0412af00: efbebeba efbebeba e0ea0200 efbebeba
> 0x0412af10: 01000000 a8ea0200 4ccd0200 dcea0200
> 0x0412af20: 10b01204 64af1204 58af1204 34f00000
> 0x0412af30: 01000000 efbebeba efbebeba efbebeba
> 0x0412af40: efbebeba efbebeba 01000000 07000000
> 0x0412af50: 10b01204 4ccd0200 78af1204 249a0000
> 0x0412af60: 78af1204 00000000 30cd0200 07000000
> 0x0412af70: 28b90200 80b90200 e8b11204 d8520000
> 0x0412af80: 1f1f1f1f 1f1f1f1f 1f1f1f1f 90970100
> 0x0412af90: c0970100 20980100 50980100 40990100
> 0x0412afa0: 68000000 00000000 3f000000 00000000
> 0x0412afb0: 00000000 00000000 01000000 02000000
> 0x0412afc0: 77000000 1f1f1f1f 1f1f1f1f 1f1f1f1f
> 0x0412afd0: 1f1f1f1f 1f1f1f1f 1f1f1f1f 1f1f1f1f
> 0x0412afe0: 1f1f1f1f 1f1f1f1f 1f1f1f1f 1f1f1f1f
> 0x0412aff0: 1f1f1f1f 00000000 00000000 a8830200
> 0x0412b000: 77000000 28600200 e8030000 13040000
> 0x0412b010: 8caf1204 08b20200 00000000 01000000
> 0x0412b020: cd000000 f0b20200 e3000000 95000000
> 0x0412b030: 03000000 03020000 01000000 01000000
> 0x0412b040: 00000000 0000f03f 00000000 00000000
> 0x0412b050: 00000000 01000000 01000000 00000000
> 0x0412b060: 02000000 01000000 00010000 00000000
> 0x0412b070: 00000000 00000000 e3000000 95000000
> 0x0412b080: 03000000 03000000 01000000 00000000
> 0x0412b090: 00000000 00000000 01000000 01000000
> 0x0412b0a0: 01000000 01000000 00000000 18b30200
> 0x0412b0b0: a0b30200 00000000 00000000 28b40200
> 0x0412b0c0: 58b60200 00000000 00000000 40b50200
> 0x0412b0d0: 70b70200 00000000 00000000 08000000
> 0x0412b0e0: 30cc0200 00000000 00000000 00000000
> 0x0412b0f0: 00000000 00000000 00000000 01010101
> 0x0412b100: 01010101 01010101 01010101 05050505
> 0x0412b110: 05050505 05050505 05050505 00000000
> 0x0412b120: 01000000 00000100 01000000 00000000
> 0x0412b130: 00000000 00000000 02000000 02000000
> 0x0412b140: 08000000 0a000000 28d10200 03000000
> 0x0412b150: 30cc0200 84cc0200 d8cc0200 00000000
> 0x0412b160: 0f000000 0a000000 06000000 00000000
> 0x0412b170: 00000000 00000000 00000000 01000000
> 0x0412b180: 02000000 00000000 00000000 00000000
> 0x0412b190: 00000000 00000000 3f000000 00000000
> 0x0412b1a0: 00000000 00000000 08d00200 a8ea0200
> 0x0412b1b0: 30ea0200 70e60200 d0b20200 70b20200
> 0x0412b1c0: e8e90200 90e60200 c0e50200 a8d50200
> 0x0412b1d0: 00000000 00000000 efbebeba efbebeba
> 0x0412b1e0: 404c0200 07000000 f8b11204 b8b80100
> 0x0412b1f0: efbebeba efbebeba 00000000 a83c0000
> 
> Done!
>         T0: Insns=210159 Tcycles=136148
>         T1: Insns=0 Tcycles=0
>         T2: Insns=0 Tcycles=0
>         Total: Insns=210159 Pcycles=408448
>         Simulator speed=2.021732 Mips
>         Ratio to Real Time (500 MHz) = ~1/127 (elapsed time = 0.103950s)
> 

[djpeg-h2v2_fancy_upsample-simulator_exception.zip](https://github.com/unison-code/unison/files/816895/djpeg-h2v2_fancy_upsample-simulator_exception.zip)

**Comment by robcasloz** [comment]
Cannot reproduce it anymore, djpeg produces now correct results.
