### ISSUE TITLE
epic does not terminate - Benchmark: epic, Function: reflect1

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#13]
When executing the code compiled with unison, the benchmark does not terminate.

`/home/martip/Qualcomm/HEXAGON_Tools/6.4.06/qc/bin/hexagon-sim epic-llvm --profile --statsfile prof_stat          _llvm.txt -- ../test_image -b 25;\`

> Hexagon-sim INFO: the rev_id used in the simulation is 0x00000084 (v4m)
> Xsize: 256, Ysize: 256.
> Building pyramid, 4 levels ...
> Quantizing, binsize = 25.000000 ...
> Run-length coding ...
> Huffman coding ...
> Low_pass_size: 256,  Symbol_stream_length: 13998,  Huffman_stream_length: 6592
> Writing EPIC file ...
> Stored 8 byte header.
> Stored 516 bytes of Raw (lowpass) Data.
> Stored 36 bytes of Binsize Info.
> Stored 280 byte Huffman tree .
> Stored 6592 bytes of encoded data.
> Storage total: 7432 bytes (0.907227 bits/pixel)
> Compression ratio = 8.818084:1.

> Done!
>         T0: Insns=1443757728 Tcycles=635857347
>         T1: Insns=0 Tcycles=0
>         T2: Insns=0 Tcycles=0
>         Total: Insns=1443757728 Pcycles=1907572045
>         Simulator speed=6.543963 Mips
>         Ratio to Real Time (500 MHz) = ~1/58 (elapsed time = 220.624371s)

`/home/martip/Qualcomm/HEXAGON_Tools/6.4.06/qc/bin/hexagon-sim epic-unison --profile --stats          file prof_stat_unison.txt -- ../test_image -b 25;\`

> Hexagon-sim INFO: the rev_id used in the simulation is 0x00000084 (v4m)
> Xsize: 256, Ysize: 256.
> Building pyramid, 4 levels ...

I've ran the simulation with the code compiled with Unison for ~40 mins without termination, while it terminates within 5 minutes with llvm.
Attached in the zip-file are the different assembly-file aswell as the source c-file
[epic-epic-reflect1-does_not_termiate.zip](https://github.com/unison-code/unison/files/821318/epic-epic-reflect1-does_not_termiate.zip)

**Comment by robcasloz** [comment]
Fixed long time ago for the experiments in https://arxiv.org/pdf/1804.02452.
