### ISSUE TITLE
over-subscribed slots - Benchmarks: unepic, g721_encode, cjpeg, Functions: read_and_huffman_decode, quantize, encode_one_block

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#18]
over-subscribed slots occured 3 times for my last builds of the benchmarks.
The log, sourcefile and unison-intermediate-files for the benchmarks are located in separate directories in the attached source-file.

The command to compile with llvm used is:
llc -O3 -unison-no-clean -unison-import-flags="--simplifycontrolflow=false" -unison-normalize-flags="--simplifycontrolflow=false" -unison-verbose -unison-solver-flags="--emit-improvement" -unison-max-instrs=1000 -unison-model-flags="--strictlybetter=false" -unison-single-function=**<function_name>**  -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o **<output_filename>** **<input_filename>**

[over-subscribed_slots.zip](https://github.com/unison-code/unison/files/833981/over-subscribed_slots.zip)

**Comment by robcasloz** [comment]
Hi @maerem, thanks for the report! I fixed the issue for `quantize`, please double-check whether the problem is also fixed for the other attached functions.
