### ISSUE TITLE
Issue when building with both qt4 and qt5 installed on system

### ISSUE THREAD

**Issue by jkimblad** [unison-code/unison#28]
**Running on:** Manjaro Linux 17.1.6

When building unison (i.e. "make build" in unison/src/) with both qt4 and qt5 installed on the system it defaults to using qt5. Thus producing the [following error](https://gist.github.com/jkimblad/fc7e8795e2986f99d8120e29871ba070).

Looking at the qt-documentation, we can indeed see that qt4 should not produce this error as it takes the right amount of arguments for QApplication, while qt5 does not.

- [Qt5 Qapplication](http://doc.qt.io/qt-5/qapplication.html) takes only two arguments for its constructor.
- [Qt4 QApplication](http://doc.qt.io/archives/qt-4.8/qapplication.html) takes three arguments for its constructor, the third being a boolean.

The problem seems to be that the command "qmake" used [here](https://github.com/unison-code/unison/blob/dc8f590bff834712e8d75c7924717a2fb8d01072/src/solvers/gecode/solver.mk#L82), [here](https://github.com/unison-code/unison/blob/dc8f590bff834712e8d75c7924717a2fb8d01072/src/solvers/gecode/solver.mk#L89), and [here](https://github.com/unison-code/unison/blob/c91bc897f45762731f047df587ee8049c829c571/src/solvers/gecode/presolver.mk#L79) defaults to using qt5 when both qt5 and qt4 exists on the system.

**Comment by jkimblad** [comment]
However, this may be something that should be fixed on the user-side and not in Unison.

**Comment by robcasloz** [comment]
Pull request #29 merged.
