### ISSUE TITLE
 Assertion "ss != SS_FAILED" failed

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#3]
**Command used to generate error:**
`llc -O3 -unison-verbose -unison-import-flags="--simplifycontrolflow=false" -unison-normalize-flags="--simplifycontrolflow=false"  -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o convolve.unison.S convolve.unison.ll`

**Output:**
`/home/martip/bin/uni: uni import --target=Hexagon /tmp/unison-f50631.mir -o /tmp/unison-f50631.uni --function=internal_filter --maxblocksize=25 --goal=speed --simplifycontrolflow=false`
`/home/martip/bin/uni: uni linearize --target=Hexagon /tmp/unison-f50631.uni -o /tmp/unison-f50631.lssa.uni`
`/home/martip/bin/uni: uni extend --target=Hexagon /tmp/unison-f50631.lssa.uni -o /tmp/unison-f50631.ext.uni`
`/home/martip/bin/uni: uni augment --target=Hexagon /tmp/unison-f50631.ext.uni -o /tmp/unison-f50631.alt.uni`
`/home/martip/bin/uni: uni normalize --target=Hexagon /tmp/unison-f50631.asm.mir -o /tmp/unison-f50631.llvm.mir --simplifycontrolflow=false`
`/home/martip/bin/uni: uni model --target=Hexagon /tmp/unison-f50631.alt.uni -o /tmp/unison-f50631.json --basefile=/tmp/unison-f50631.llvm.mir +RTS -K20M -RTS`
`/home/martip/bin/gecode-presolver: gecode-presolver -o /tmp/unison-f50631.ext.json /tmp/unison-f50631.json`
`/home/martip/bin/gecode-solver: gecode-solver -o /tmp/unison-f50631.out.json --verbose /tmp/unison-f50631.ext.json`

> gecode-solver: solver.cpp:594: int main(int, char**): Assertion `ss != SS_FAILED' failed.
> *** Aborted (core dumped) ***

[assertion_error.zip](https://github.com/unison-code/unison/files/787364/assertion_error.zip)

**Comment by robcasloz** [comment]
Cannot reproduce the failure anymore, most likely solved by commit 0fbcc132b4576934ab384df7f523be643ca004da.
