### ISSUE TITLE
Questions regarding setup

### ISSUE THREAD

**Issue by vmiheer** [unison-code/unison#33]
Does it need Qt 4 or it can work with Qt 5? I got Qt installer (.run file) and even the archive doesn't show 4.0 versions. The oldest version it lists is 5.9.0

**Comment by robcasloz** [comment]
Hi @vmiheer, it is possible that Unison works with newer versions of Qt, but we have not tried it yet.
Anyway, Qt is an optional dependency, you can disable it by building as follows:
```
make build UNISON_SOLVER_CONFIG=""
```
The default value for `UNISON_SOLVER_CONFIG` is `GRAPHICS` which builds the solver and presolver with visualizations using Qt.

With `UNISON_SOLVER_CONFIG=""`, the build system still uses `qmake`, but hopefully you can use later versions of it.

Best Regards,

Roberto

**Comment by robcasloz** [comment]
Hi again @vmiheer, just for the record: Unison supports Qt 5 now. Better late than never ;)
