### ISSUE TITLE
Documentation Request: Refine the specification on the API functions

### ISSUE THREAD

**Issue by DKXXXL** [unison-code/unison#35]
I am currently trying to target to a private backend but I have many issues on understanding the specification of those required functions in API. The comments themselves are too vague for an implementation.

**Comment by robcasloz** [comment]
Hi @DKXXXL, thank you for feedback! As you mention, the documentation of Unison's target description functions is currently a bit lacking. I have just added a description of two current sources of documentation to https://github.com/unison-code/unison/blob/master/README.md, just to ensure that they are not overlooked.

A useful approach is to look at how other targets are implemented, in particular the Hexagon target which is the most mature at the moment.

If you provide more detail about the functions that you find underspecified and what kind of additional information you would like to see, I might be able to improve their documentation (either in the manual or in the source code).

**Comment by DKXXXL** [comment]
Thx. I will open new issues on each specific questions so that possible future documentation can be easier.
