### ISSUE TITLE
Queries related multi_backend (minizinc)

### ISSUE THREAD

**Issue by utkarshyen** [unison-code/unison#44]
Hello @robcasloz 

I have some queries regarding the multi-backend of unison.
Pre-requisite:
- I tried default unison with default gecode solver for a convolution sample. It works fine.
- I then tried same sample using ./minizinc-solver script with other solvers, where I found some of the JSON operands (like op_order) are missing from code-generation.mzn file.
- After those changes in the code-generation.mzn file, the array out of bound issue.
---------------------------------------------------
$./minizinc-solver -o del.json unison-b2dbc4.ext.json
MiniZinc: result of evaluation is undefined: 
  <home>/unison/src/solvers/multi_backend/minizinc/unison-b2dbc4.mzn:1293:
  in call 'forall'
  in array comprehension expression
    with bb = 1
  <home>/unison/src/solvers/multi_backend/minizinc/unison-b2dbc4.mzn:1294:
  in let expression
<home>/unison/src/solvers/multi_backend/minizinc/unison-b2dbc4.mzn:1295:
  in call 'array1d'
  in array comprehension expression
    with o = 0
  in call 'o_wcet'
<home>/unison/src/solvers/multi_backend/minizinc/unison-b2dbc4.mzn:1300:
  in let expression
  in array comprehension expression
    with jj = 1
  in array access
  array access out of bounds
---------------------------------------------------

This is my understanding of the how multi-backend works
> unison.ext.json => unison.dzn (using sicstus tool) 
> code-generation.mzn + topdown.mzn = unison.mzn (from minizinc folder)

- Is there anything I'm are missing? Please note, I'm new to minizinc format.
- Also I found link in doc (https://www.minizinc.org/doc-2.4.1/en/flattening.html (2.8.4. section Arrays)) which says, in flatzinc array index starts with "1".

Regards,
UT

**Comment by utkarshyen** [comment]
Hello @robcasloz 

Any update on the same? I could not get any clue on this.
Tried changing the array value and syntax but no success.

Regards,
UT

**Comment by robcasloz** [comment]
Hi @utkarshyen, thank you for the report. The usage of the MiniZinc back-end should be better documented and perhaps simplified, sorry about that!

The standard procedure is to generate a .dzn file using `gecode-presolver -dzn FILE.dzn` and then pass `FILE.dzn` as input to `minizinc-solver`, SICStus Prolog is not required anymore.  Assuming you have generated a JSON parameters file `unison.json`, the command sequence would be:

```
gecode-presolver  -dzn unison.dzn unison.json
minizinc-solver -o unison.out.json -dzn unison.dzn DUMMY_FILENAME
```

Note that you can discard the JSON file printed to stdout by `gecode-presolver` (that would be the input to `gecode-solver`), and that the positional argument of `minizinc-solver` (`DUMMY_FILENAME`) is just ignored (this is left for backwards compatibility). 

Assuming that the directories `src/solvers/multi_backend/common` and `src/solvers/multi_backend/minizinc` within the Unison repo are in the `PATH`, `minizinc-solver` should take care of the rest.

Hope that helps!

**Comment by utkarshyen** [comment]
Hi @robcasloz, Thank you for detailed info.
I could execute the steps you mentioned. However, after solving I could see solution as "unsatisfiable".

-----------------------------------------------------------
=====UNSATISFIABLE=====
%%%mzn-stat: objective=0
%%%mzn-stat: objectiveBound=0
%%%mzn-stat: boolVariables=0
%%%mzn-stat: failures=0
%%%mzn-stat: propagations=0
%%%mzn-stat: solveTime=0.296174
%%%mzn-stat: nSolutions=0
-----------------------------------------------------------

Whereas, if I use the actual default unison with llvm below is gecode-solver output,

-----------------------------------------------------------
[global] variables: 13329 int, 21665 bool, 971 set
[global] proven absence of solutions with cost less or equal than {9381}
execution time: 308.937 ms
-----------------------------------------------------------

May be the issue with the model. Once again thank you for the steps, I'll look into this more.
> Hope that helps!

It was helpful.

Regards,
UT

**Comment by robcasloz** [comment]
Great! From the output you provide, it looks like the solvers are proving in both cases that the solution provided by LLVM is already optimal (the cost of LLVM's heuristic solution is given to the Unison solvers as an upper bound).
