### ISSUE TITLE
Queries regarding few .hs files like Common.hs, Transform.hs, <target_name>.hs in unison backend

### ISSUE THREAD

**Issue by utkarshyen** [unison-code/unison#52]
Exploring the files like Common.hs, Transform.hs, etc
What is the purpose of these files? For reference I have gone through for different target like ARM and Hexagon, which gave me a brief picture.

Although, the target.yaml file is important for the target instructions usage and SLOT details and generated from llvm-tblgen it contains all the target specific instructions. Then why these additional file like target-manual.yaml and target-remat.yaml are?

Can you please give some clear idea regarding all these files? I could not find in documentation. Sorry If I missed anything.

Regards,
Utkarsh

**Comment by utkarshyen** [comment]
Hello @robcasloz 

We are trying to add the backend for proprietary target. However, we are facing some difficulties in understanding the respective files mentioned above.
> For e.g. from target.hs file we could see some functions like fromcopy, cmpComboVersions, etc. And we are not sure exactly what they do. Are they specific to Hexagon?

We have our target.yaml file which seems to be fine as unison is built successfully, however we could see few other instructions floating. We have been taking Hexagon as a reference.
After few investigation the above mentioned functions/logics are specific to hexagon (Correct me if I’m wrong).
Also checking other target (ARM, Mips) files too.

Can you please brief and guide us in understanding the flow and understanding these **BOLD marked** files which we can map it to our target.

├── **Common.hs**
├── **HexagonRegisterDecl.hs**
├── **HexagonResourceDecl.hs**
├── **Registers.hs**
├── SpecsGen
│   ├── AlignedPairs.hs
│   ├── AllInstructions.hs
│   ├── HexagonInstructionDecl.hs
│   ├── HexagonItineraryDecl.hs
│   ├── HexagonRegisterClassDecl.hs
│   ├── input
│   │   ├── **hexagon-manual.yaml**
│   │   ├── **hexagon-remat.yaml**
│   │   └── hexagon.yaml
│   ├── InstructionType.hs
│   ├── Itinerary.hs
│   ├── OperandInfo.hs
│   ├── Parent.hs
│   ├── ReadOp.hs
│   ├── ReadWriteInfo.hs
│   ├── ShowInstance.hs
│   └── Size.hs
├── SpecsGen.hs
├── **Transforms.hs**
└── **Usages.hs**

We could figured few files like HexagonRegisterDecl.hs, HexagonResourceDecl.hs, Register.hs and Usages,hs, but still their is a gap with other files.

PS – We tried replacing the instructions with the reference .hs file, unison got built however while running a sample we got below error,
>uni: Prelude.!!: index too large

Any idea on above too?

**Comment by robcasloz** [comment]
Hi @utkarshyen,

The target-specific part of Unison is poorly documented, I wish I had the time to complete Chapter 7 in the [Unison manual](https://unison-code.github.io/doc/manual.pdf). Anyway, If you haven't done it yet, please have a look at that first.

All these files form a template that we found useful to arrange the target-specific parts of the code, but it is not at all mandatory to have the same file structure for all targets. After all, a target is "just" a data structure of type `TargetDescription` with some target-dependent parameters. In the existing target descriptions:
- `Common.hs` contains utility functions such as predicates that are often shared by other modules in the target description,
- `Transforms.hs` includes target-specific Unison IR transformations that are invoked at different points of the Unison pipeline as requested by the target function `transforms`, and
- `Usages.hs` maps target instructions to their lists of resource usages (see the data type `Usage` in `Base.hs`).

Regarding the YAML files:
- `<TARGET>-manual.yaml` declares pseudo-instructions that are used temporarily through the Unison pipeline to hide or expose certain information to Unison, among others copy pseudo-instructions to be returned by the `copies` target description function and transformed into "real" instructions by the `fromCopy` target description function (see Section 4.4 [in this paper](https://arxiv.org/pdf/1804.02452.pdf) for background); and
- `<TARGET>-remat.yaml` declares instructions that can be rematerialized and from which Unison derives an additional set of pseudo-instructions (see Section 4.5 [in the same paper](https://arxiv.org/pdf/1804.02452.pdf) for background). I recommend you to omit rematerialization in the initial version of your target description (by always returning `Nothing` in `rematInstrs`) and only deal with it later when everything else works.

Perhaps the simplest way to debug problems like the one you encounter is to examine the Unison IR after each transformation in the tool chain (with the `debug` option) and also run Unison with linting enabled (with the `lint` option).

**Comment by utkarshyen** [comment]
Hello @robcasloz 

Thank you for the detailed description of the files.
Let me start understanding it more with reference to Hexagon and try to port these files for our target.
However, I might be more specific in query as I get more deep.

Regards,
Utkarsh

**Comment by robcasloz** [comment]
Hi again,

You might be interested in the newly added `Minimal` target, a minimal working target implementation that can serve as a template for creating new targets. See [Section 7.1 in the Unison manual](https://unison-code.github.io/doc/manual.pdf#section.7.1) for more details.

**Comment by utkarshyen** [comment]
Thank you @robcasloz for the minimal working target.

Regards,
Utkarsh

**Comment by utkarshyen** [comment]
Hello @robcasloz ,

I have been looking into the Minimal Target. I have few queries regarding the autogenerated files (SpecsGen/*.hs) by specgen.
I tried running the command manually as below,

**$make run-specsgen-minimal**
```
specsgen --targetname=Minimal unison/src/Unison/Target/Minimal/SpecsGen/input/minimal.yaml  \
         --outputdir=unison/src/Unison/Target/Minimal/SpecsGen \
         --infiniteregclass M32
specsgen: src/SpecsGen/SimpleYaml.hs:95:1-45: Non-exhaustive patterns in function yLookup

Makefile:189: recipe for target 'run-specsgen-minimal' failed
make: *** [run-specsgen-minimal] Error 1

```
Similarly, for our target we don't have target-remat.yaml file. We tried removing it from command to generate the *.hs files using specgen, **we could get the similar error as above.**

**Any idea about this? Can you provide us the pointer, how these files are generated for Minimal target?**

PS - Other specgen command for targets like Hexagon, ARM, MIPS are working as expected and they have target-remat file.
Also, we tried passing the empty (commented code) remat file to our target and run-specgen-target seems to be working.

Regards,
Utkarsh

**Comment by robcasloz** [comment]
Hi @utkarshyen,

Commit cdf9c45 addressed this problem, did you rebuild and reinstall specsgen (`make build-specsgen && sudo make install-specsgen` or similar) before running your command?

**Comment by utkarshyen** [comment]
Hello @robcasloz,

Thank you for the pointer.
We could make use of the Minimal Target for our target porting.
We have done most of the things, however we are facing operand mismatch issue.
Please note, we have used lint (-l) option for debug messages.
```
...
...
consistentOperands: in operation o237, the number of operands and the number of operand info items from the target description do not match
consistentOperands: in operation o238, the number of operands and the number of operand info items from the target description do not match
consistentOperands: in operation o239, the number of operands and the number of operand info items from the target description do not match
consistentOperands: in operation o240, the number of operands and the number of operand info items from the target description do not match
noMustConflicts: conflicting pre-assignments in o0: [t0:r5,t3:r5]
noMustConflicts: conflicting pre-assignments in o0: [t1:r6,t4:r6]
```

We suspect to be the issue in below part of code.
```
copies (f, cst, _, _, _, _) False t [_] _d [_u]
  | S.member t cst =
    (
      if isEntryTemp (fCode f) t
      then [mkNullInstruction, TargetInstruction Store]
      else [],
      [if isExitTemp (fCode f) t
       then [mkNullInstruction, TargetInstruction Load]
       else []]
    )
copies _ _ _ _ _d us = (defCopies, replicate (length us) useCopies)

defCopies = [mkNullInstruction] ++ map TargetInstruction [Move, Store]
useCopies = [mkNullInstruction] ++ map TargetInstruction [Move, Load]

```
We have replaced out **Store**, **Load** and **Move** copies type with our instructions.
I'm not much aware of the significance of **Move** instructions as these copy instructions are transform into their real corresponding instructions. it replaces unison pseudo instructions to target linear instructions. Please correct me if I'm wrong.

It will be very much helpful to get guidance from you.

Regards,
Utkarsh

**Comment by robcasloz** [comment]
> consistentOperands: in operation o237, the number of operands and the number of operand info items from the target description do not match
> consistentOperands: in operation o238, the number of operands and the number of operand info items from the target description do not match
> consistentOperands: in operation o239, the number of operands and the number of operand info items from the target description do not match
> consistentOperands: in operation o240, the number of operands and the number of operand info items from the target description do not match

Without knowing what operations o237-o240 are, it is hard to give much guidance, but what `consistentOperands` complains about is that the instructions implementing these operations have a mismatching number of use and define operands in the SpecsGen entry and in the linted Unison IR. For example, for the following Unison IR operation:
```
o8: [t2] <- sub [t1,t6]
```
we expect the SpecsGen entry of `sub` to have one definition operand and two use operands:
```
        - id:                 sub
          ...
          operands:
           - dst:             [register, def, R32]
           - src1:            [register, use, R32]
           - src2:            [register, use, R32]
          uses:               [src1, src2]
          defines:            [dst]
          ...
```
 
> We have replaced out **Store**, **Load** and **Move** copies type with our instructions and may be we have messed up something in this part of code.
> ...
> From above debug messages it feels that we need to have same operand list in the Store and our store instruction from target.yaml file.

This is correct.

> I'm not much aware of the significance of **Move** instructions as these copy instructions are transformed into their real corresponding instructions. It replaces unison pseudo instructions to target linear instructions. Please correct me if I'm wrong.

You're right, think about the **Move** instructions as abstract versions of the register-to-register moves, like for example ARM's `MOV dst, src` instruction.

The following discussion might be relevant: https://github.com/unison-code/unison/issues/36.

**Comment by utkarshyen** [comment]
Hello @robcasloz ,

Thank you for comment.
After a bit investigation, we found that the instruction which we are replacing with **"Move"** is causing an issue.

Will look into this more.

**Comment by utkarshyen** [comment]
Hello @robcasloz ,

Can you provide me brief info regarding the usages syntax as below
```
...
slot3       = oneOfSlot23 ++ [mkUsage Slot3 1 1]
store n     = [mkUsage Store n 1]
...
```
What does the bits '1' '1' indicates?

Regards,
Utkarsh

**Comment by robcasloz** [comment]
> slot3       = oneOfSlot23 ++ [mkUsage Slot3 1 1]
> (...)
> What does the bits '1' '1' indicates?

`mkUsage Slot3 1 1` gives an usage of 1 unit of `Slot3` during 1 cycle. In general,`mkUsage r u o` gives a Usage of `u` units of resource `r` with occupation (duration of the usage) `o`. 

You can find more information about the basic Unison types (including `Usage`) by generating the HTML documentation, see [Section 7.1 in The Unison Manual](https://unison-code.github.io/doc/manual.pdf#section.7.1). The relevant module is `Unison.Base`.

**Comment by utkarshyen** [comment]
Hello @robcasloz 

Thank you for your inputs,
However, closing this query as all the doubts scoping in this request we done.

Created a new request https://github.com/unison-code/unison/issues/55 

Regards,
Utkarsh
