### ISSUE TITLE
Running out of memory - Benchmark: epic, Function: quantize_image

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#6]
`llc -O3 -unison-verbose -unison-no-clean -unison-import-flags="--simplifycontrolflow=false" -unison-normalize-flags="--simplifycontrolflow=false" -unison-single-function=quantize_image  -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o unison_build_quantize_image/quantize.S unison_build_quantize_image/quantize.ll`

[epic-quantize_image-memory_leak.zip](https://github.com/unison-code/unison/files/813343/epic-quantize_image-memory_leak.zip)

**Comment by maerem** [comment]
Another instance of this occuring:
Benchmark: epic, Function: reflect1

`llc -O3 -unison-verbose -unison-no-clean -unison-import-flags="--simplifycontrolflow=false" -unison-normalize-flags="--simplifycontrolflow=false" -unison-single-function=reflect1  -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o unison_build_reflect1/edges.S unison_build_reflect1/edges.ll`

`martip@bobito:~/benchmarks/epic/epic$ uni count /tmp/unison-fc5bea.uni`

> Name unison-fc5bea
> Blocks 58
> Operations 436
> Operations-per-block 7.517241379310345
> Maximum-operations-in-block 28
> Copies 12
> Operands 1085
> Operands-per-in-delimiter 0.25862068965517243
> Maximum-operands-in-an-in-delimiter 15
> Operands-per-out-delimiter 0.1724137931034483
> Maximum-operands-in-an-out-delimiter 10
> Temporaries 325
> Rematerialization-points 0
> Split-blocks 4

[epic-reflect1-memory_leak.zip](https://github.com/unison-code/unison/files/813784/epic-reflect1-memory_leak.zip)

**Comment by robcasloz** [comment]
Commit 9ed363969b74221ab249e9cb3f06fb1d00c2d5ae also reduces significantly the memory consumption.
