### ISSUE TITLE
Assembler: Register `r31/lr' modified more than once - Benchmark: g721_encode, Function: predictor_zero

### ISSUE THREAD

**Issue by maerem** [unison-code/unison#9]
`llc -O3 -unison-no-clean -unison-import-flags="--simplifycontrolflow=false" -unison-normalize-flags="--simplifycontrolflow=false" -unison-solver-flags="--emit-improvement" -unison-max-instrs=1000 -unison-verbose -unison-single-function=predictor_zero  -march=hexagon -mcpu=hexagonv4 -disable-post-ra -disable-tail-duplicate -disable-branch-fold -disable-block-placement -disable-phi-elim-edge-splitting -disable-hexagon-cfgopt -disable-if-conversion -o unison_build_predictor_zero/g72x.S unison_build_predictor_zero/g72x.ll`

> /home/martip/bin/uni: uni import --target=Hexagon /tmp/unison-c2ce16.mir -o /tmp/unison-c2ce16.uni --function=predictor_zero --maxblocksize=25 --goal=speed --simplifycontrolflow=false
> /home/martip/bin/uni: uni linearize --target=Hexagon /tmp/unison-c2ce16.uni -o /tmp/unison-c2ce16.lssa.uni
> /home/martip/bin/uni: uni extend --target=Hexagon /tmp/unison-c2ce16.lssa.uni -o /tmp/unison-c2ce16.ext.uni
> /home/martip/bin/uni: uni augment --target=Hexagon /tmp/unison-c2ce16.ext.uni -o /tmp/unison-c2ce16.alt.uni
> /home/martip/bin/uni: uni normalize --target=Hexagon /tmp/unison-c2ce16.asm.mir -o /tmp/unison-c2ce16.llvm.mir --simplifycontrolflow=false
> /home/martip/bin/uni: uni model --target=Hexagon /tmp/unison-c2ce16.alt.uni -o /tmp/unison-c2ce16.json --basefile=/tmp/unison-c2ce16.llvm.mir +RTS -K20M -RTS
> /home/martip/bin/gecode-presolver: gecode-presolver -o /tmp/unison-c2ce16.ext.json /tmp/unison-c2ce16.json
> /home/martip/bin/gecode-solver: gecode-solver -o /tmp/unison-c2ce16.out.json --verbose --emit-improvement /tmp/unison-c2ce16.ext.json
> [global] variables: 2821 int, 4485 bool, 235 set
> [global] cost: [21..24], optimality gap: 14.29%
> [pre]    computing effective callee-saved copies...
> [pre]    presolving time (effective callee-saved spilling): 26 ms
> [pre]    computing lower bounds...
...

> [global] found optimal solution
> execution time: 54221.5 ms
> total failed nodes in all problems: 227119
> total searched nodes in all problems: 458348
> optimal solution has cost: 21, improvement: 19.05%
> cost: 21, improvement: 19.05%
> /home/martip/bin/uni: uni export --target=Hexagon /tmp/unison-c2ce16.alt.uni -o /tmp/unison-c2ce16.unison.mir --basefile=/tmp/unison-c2ce16.llvm.mir --solfile=/tmp/unison-c2ce16.out.json
> /home/martip/Qualcomm/HEXAGON_Tools/6.4.06/gnu/bin/hexagon-as -mv4 --gdwarf2 --keep-locals -o unison_build_predictor_zero/g72x.o unison_build_predictor_zero/g72x.S
> unison_build_predictor_zero/g72x.S: Assembler messages:
> unison_build_predictor_zero/g72x.S:131: **Error: register `r31/lr' modified more than once.**

## Instruction bundle at unison_build_predictor_zero/g72x.S:131
	{
			r0 = asr(r0, #2)
			call fmult
			r21:20 = memd(r29 + #16)
			deallocframe
	}
[g721_encode-predictor_zero-register_modified_more_than_once.zip](https://github.com/unison-code/unison/files/816258/g721_encode-predictor_zero-register_modified_more_than_once.zip)

**Comment by robcasloz** [comment]
Hi @maerem, commit 90710ed6 should fix the regression bug introduced when fixing this one.
